### ISSUE TITLE
Run best button not working / high score not resetting 

### ISSUE THREAD

**Issue by charbelsako** [shiffman/NOC-S18#1]
#issue detected in **week10** flappy bird  
# run best button 
#### i was attempting to run this on my phone. And when i clicked on the run best button it launches the best neural network yet and then it launches the training immediately right after that. 

# high score
#### when running the "best so far" the high score never resets itself even after the agent lost the game

**Comment by shiffman** [comment]
I fixed the high score problem with https://github.com/shiffman/NOC-S18/commit/6d105176bb4f91fb7c43e6e6d9bcdcdff3ba6c35. Right now I am not supporting mobile so will close this issue, but a pull request if it's a simple fix to make it work on mobile I'll gladly accept.
